import { ChapterDefinition } from '../types/game';

export const ALL_CHAPTERS: ChapterDefinition[] = [
  {
    id: 1,
    numberPrefix: '1',
    name: 'Verdant Prairie',
    stagesCount: 50,
    theme: 'verdant',
    description: 'A lush primordial grassland overrun by savage flora, goblin archers, and the Moss Colossus.',
    recommendedAtk: 40,
    recommendedHp: 500,
    icon: '🌿',
    bossName: 'Ancient Moss Golem',
    themeColors: {
      floorPrimary: 0x1e3a1e,
      floorSecondary: 0x244724,
      wallColor: 0x0f2412,
      accentColor: '#4ade80',
      ambientGlow: 'rgba(74, 222, 128, 0.15)',
    },
  },
  {
    id: 2,
    numberPrefix: '2',
    name: 'Dungeon Depths',
    stagesCount: 50,
    theme: 'dungeon',
    description: 'Subterranean stone crypts echoing with the footsteps of armored chargers and death snipers.',
    recommendedAtk: 120,
    recommendedHp: 1200,
    icon: '🏰',
    bossName: 'Minotaur Warlord',
    themeColors: {
      floorPrimary: 0x1e293b,
      floorSecondary: 0x334155,
      wallColor: 0x090d16,
      accentColor: '#38bdf8',
      ambientGlow: 'rgba(56, 189, 248, 0.15)',
    },
  },
  {
    id: 3,
    numberPrefix: '3',
    name: 'Desert Oasis',
    stagesCount: 50,
    theme: 'desert',
    description: 'Scorching sunbaked dunes with subterranean sand worms, venom scorpions, and cursed tombs.',
    recommendedAtk: 260,
    recommendedHp: 2200,
    icon: '🏜️',
    bossName: 'Pharaoh of the Sunken Crypt',
    themeColors: {
      floorPrimary: 0x452a12,
      floorSecondary: 0x5c3917,
      wallColor: 0x2b1708,
      accentColor: '#fbbf24',
      ambientGlow: 'rgba(251, 191, 36, 0.18)',
    },
  },
  {
    id: 4,
    numberPrefix: '4',
    name: 'Crystal Caverns',
    stagesCount: 50,
    theme: 'crystal',
    description: 'A subterranean cavern filled with luminescent sapphire crystals and freezing frost elementals.',
    recommendedAtk: 480,
    recommendedHp: 3600,
    icon: '💎',
    bossName: 'Frost Glacial Leviathan',
    themeColors: {
      floorPrimary: 0x172554,
      floorSecondary: 0x1e3a8a,
      wallColor: 0x0c1222,
      accentColor: '#818cf8',
      ambientGlow: 'rgba(129, 140, 248, 0.2)',
    },
  },
  {
    id: 5,
    numberPrefix: '13',
    name: 'Lava Land',
    stagesCount: 50,
    theme: 'lava',
    description: 'Rivers of boiling molten magma, volcanic dragons, fiery skulls, and crumbling brimstone ruins.',
    recommendedAtk: 850,
    recommendedHp: 5800,
    icon: '🌋',
    bossName: 'Infernal Magma Dragon',
    themeColors: {
      floorPrimary: 0x3b0704,
      floorSecondary: 0x4a0a06,
      wallColor: 0x200302,
      accentColor: '#f97316',
      ambientGlow: 'rgba(249, 115, 22, 0.25)',
    },
  },
  {
    id: 6,
    numberPrefix: '6',
    name: 'Sky Sanctuary',
    stagesCount: 50,
    theme: 'sky',
    description: 'Floating marble temples above the clouds guarded by divine seraphim and storm valkyries.',
    recommendedAtk: 1350,
    recommendedHp: 8500,
    icon: '☁️',
    bossName: 'Thunder God Valkyrie',
    themeColors: {
      floorPrimary: 0x1e385c,
      floorSecondary: 0x2d4f7c,
      wallColor: 0x0f1c30,
      accentColor: '#67e8f9',
      ambientGlow: 'rgba(103, 232, 249, 0.2)',
    },
  },
  {
    id: 7,
    numberPrefix: '7',
    name: 'Void Abyss',
    stagesCount: 50,
    theme: 'void',
    description: 'An otherworldly cosmic tear in spacetime inhabited by reality-warping void specters.',
    recommendedAtk: 2100,
    recommendedHp: 12500,
    icon: '🌌',
    bossName: 'Void Sovereign Archon',
    themeColors: {
      floorPrimary: 0x2e0854,
      floorSecondary: 0x3b0764,
      wallColor: 0x170329,
      accentColor: '#c084fc',
      ambientGlow: 'rgba(192, 132, 252, 0.25)',
    },
  },
  {
    id: 8,
    numberPrefix: '8',
    name: "Hero's Peak",
    stagesCount: 50,
    theme: 'peak',
    description: 'The pinnacle summit where only supreme legends test their mastery against celestial titans.',
    recommendedAtk: 3200,
    recommendedHp: 18000,
    icon: '👑',
    bossName: 'Celestial Apex Deity',
    themeColors: {
      floorPrimary: 0x2e2411,
      floorSecondary: 0x3d3017,
      wallColor: 0x191307,
      accentColor: '#facc15',
      ambientGlow: 'rgba(250, 204, 21, 0.25)',
    },
  },
];
