import { HeroDefinition } from '../types/game';

export const ALL_HEROES: HeroDefinition[] = [
  {
    id: 'atreus',
    name: 'Atreus',
    title: 'The Forest Archer',
    icon: '🏹',
    baseAttackBonus: 0,
    baseHpBonus: 100,
    speedBonus: 10,
    passiveName: 'Agile Stride',
    passiveDesc: '+10 Movement Speed and +100 Base HP for high dodge maneuvers.',
    unlocked: true,
    unlockCostGems: 0,
  },
  {
    id: 'urasil',
    name: 'Urasil',
    title: 'Venom Stalker',
    icon: '🐍',
    baseAttackBonus: 25,
    baseHpBonus: 50,
    speedBonus: 0,
    passiveName: 'Toxic Dart',
    passiveDesc: 'Innate poison arrows: Arrows poison targets dealing 40% damage over 3 seconds.',
    element: 'poison',
    unlocked: true,
    unlockCostGems: 0,
  },
  {
    id: 'phoren',
    name: 'Phoren',
    title: 'Flame Warrior',
    icon: '🔥',
    baseAttackBonus: 35,
    baseHpBonus: 80,
    speedBonus: 5,
    passiveName: 'Inferno Touch',
    passiveDesc: 'Innate fire arrows: Arrows ignite enemies dealing rapid burn ticks on hit.',
    element: 'blaze',
    unlocked: true,
    unlockCostGems: 50,
  },
  {
    id: 'helix',
    name: 'Helix',
    title: 'Berserker Champion',
    icon: '🪓',
    baseAttackBonus: 50,
    baseHpBonus: 150,
    speedBonus: 0,
    passiveName: 'Fury',
    passiveDesc: 'Increases attack power proportionally as health drops (up to +120% Attack).',
    unlocked: false,
    unlockCostGems: 120,
  },
  {
    id: 'meowgik',
    name: 'Meowgik',
    title: 'Spirit Sorcerer',
    icon: '🐱',
    baseAttackBonus: 40,
    baseHpBonus: 120,
    speedBonus: 15,
    passiveName: 'Spirit Cat Summon',
    passiveDesc: 'Chance on shooting to spawn homing arcane spirit cats that track down enemies.',
    unlocked: false,
    unlockCostGems: 180,
  },
  {
    id: 'shade',
    name: 'Shade',
    title: 'Shadow Assassin',
    icon: '🌑',
    baseAttackBonus: 65,
    baseHpBonus: 60,
    speedBonus: 20,
    passiveName: 'Shadow Stealth',
    passiveDesc: 'Grants +12% Crit Rate and +10% Dodge Chance in all dungeon encounters.',
    unlocked: false,
    unlockCostGems: 250,
  },
];
